// Central Type Definitions for Linkty
// NOW POWERED BY ZOD SCHEMAS

import type {
  ILink,
  IImage,
  ISectionData,
  IHeroData,
  IBentoItem,
  IBentoGridData,
  IFeatureShowcaseData,
  ITimelineStep,
  IProcessTimelineData,
  IFaqItem,
  IFaqData,
  IFinalCtaData,
  IStatItem,
  IStatsSectionData,
  ISolutionCard,
  ISplitSolutionsData,
  ICardStackItem,
  ICardStackData,
  ICustomCard,
  ICustomSectionData,
  ITestimonialAuthor,
  ITestimonial,
  ITestimonialsData,
  ILogoItem,
  ILogoMarqueeData,
} from "../schemas/contentSchemas";

export type {
  ILink,
  IImage,
  ISectionData,
  IHeroData,
  IBentoItem,
  IBentoGridData,
  IFeatureShowcaseData,
  ITimelineStep,
  IProcessTimelineData,
  IFaqItem,
  IFaqData,
  IFinalCtaData,
  IStatItem,
  IStatsSectionData,
  ISolutionCard,
  ISplitSolutionsData,
  ICardStackItem,
  ICardStackData,
  ICustomCard,
  ICustomSectionData,
  ITestimonialAuthor,
  ITestimonial,
  ITestimonialsData,
  ILogoItem,
  ILogoMarqueeData,
};
